# Copyright Intel Corporation

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: etcd-provision-input
data:
  eii_config.json: |-
{{ .Files.Get "eii_config.json" | indent 4 }}
